


# a: b
# 	@echo $?

# b:
# 	@exit 1


# a=web server				



# dev:
# 	echo "|$(a)|"




NO=\x1b[0m
GREEN=\x1b[32;01m
RED=\x1b[31;01m
YELLOW=\x1b[33;01m

dev:
	NODE_ENV=dev ./node_modules/.bin/gulp

product:
	NODE_ENV=product ./node_modules/.bin/gulp


.PHONY: jar












